# input.yaml
dataset:
  name: "Dataset001_imagesTr"
  root_dir: "/root/autodl-tmp/work_dir/nnUNet_raw_data_base/Dataset001_imagesTr"
  splits_file: "/root/autodl-tmp/work_dir/nnUNet_raw_data_base/Dataset001_imagesTr/dataset.json"
  nnunet_preprocessed: "./work_dir/nnUNet_preprocessed"
  nnunet_raw: "./work_dir/nnUNet_raw_data_base"
  nnunet_results: "./work_dir/nnUNet_trained_models"

training:
  epochs: 100
  batch_size: 2
  optimizer:
    type: "AdamW"
    lr: 1e-3
    weight_decay: 3e-5
  lr_scheduler:
    type: "PolyLr"
    power: 0.9
    min_lr: 1e-6
  loss:
    type: "DiceCELoss"
    dice_weight: 0.5
    ce_weight: 0.5
    ignore_index: -100

augmentation:
  spatial:
    type: "Compose"
    transforms:
      - "Rotate90": { prob: 0.5 }
      - "RandAffine": { prob: 0.5, translate_range: 10 }
      - "RandFlip": { prob: 0.5, spatial_axis: [0,1,2] }
  intensity:
    type: "Compose"
    transforms:
      - "RandGaussianNoise": { prob: 0.1, std: 0.1 }
      - "RandAdjustContrast": { prob: 0.2, gamma: (0.7, 1.3) }
  use_nnunet_default_aug: True

advanced:
  amp: True
  gradient_clipping: 1.0
  num_workers: 8
  use_multi_gpu: True
  checkpoint_interval: 50