modality: CT
dataroot: "/home/lirongyaoper/Softwares/work_dir/nnUNet_raw_data_base/Dataset001_imagesTr"
datalist: "./work_dir/nnUNet_raw_data_base/Dataset001_imagesTr/dataset.json"
nnunet_preprocessed: "./work_dir/nnUNet_preprocessed" 
nnunet_raw: "./work_dir/nnUNet_raw_data_base" 
nnunet_results: "./work_dir/nnUNet_trained_models"
dataset_name_or_id: 1
preprocessing:
  intensity_normalization: "zscore"
training:
  max_epochs: 200
  batch_size: 2
  learning_rate: 0.001
  optimizer: "AdamW"
  loss: "DiceCE"
  use_amp: True
  save_interval: 50
augmentation:
  rotation: [ -15, 15 ]
  scaling: [ 0.8, 1.2 ]
  elastic_deform: True